### PR TITLE
Pl 25

### PR DESCRIPTION
**Pull request by monsterlady**

### CODE REVIEW

**Comment by JorikTaal** [comment]
Comments could use some work, a lot of them look unfinished. Also it's better to use FixedUpdate() instead of Update(). Aside from that it looks good.

**Review by JorikTaal — CHANGES_REQUESTED** [review]
Comments could use some work, a lot of them look unfinished. Also it's better to use FixedUpdate() instead of Update(). Aside from that it looks good.

**Review by JorikTaal — APPROVED** [review]

**Review by JorikTaal — CHANGES_REQUESTED** [review]
No wait shit ignore that approval, I messed up.

**Comment by monsterlady** [comment]
> No wait shit ignore that approval, I messed up.

< np XD, just push another commit, changed some stuff and add the comments

**Review by JorikTaal — APPROVED** [review]

**Pull request merged**
